import { Podcast, Episode, Recommendation } from "@/types";

export const mockPodcasts: Podcast[] = [
  {
    id: "1",
    name: "The Tim Ferriss Show",
    youtubeChannelId: "@timferriss",
    rssFeedUrl: "https://tim.blog/podcast",
    category: "Business & Self-Improvement",
    imageUrl: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=400",
    createdAt: "2024-01-01T00:00:00Z",
    lastFetchedAt: "2024-11-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Huberman Lab",
    youtubeChannelId: "@hubermanlab",
    rssFeedUrl: "https://hubermanlab.com/feed",
    category: "Science & Health",
    imageUrl: "https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=400",
    createdAt: "2024-01-01T00:00:00Z",
    lastFetchedAt: "2024-11-01T00:00:00Z",
  },
  {
    id: "3",
    name: "The Joe Rogan Experience",
    youtubeChannelId: "@joerogan",
    rssFeedUrl: "https://joerogan.com/podcast",
    category: "Comedy & Conversation",
    imageUrl: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400",
    createdAt: "2024-01-01T00:00:00Z",
    lastFetchedAt: "2024-11-01T00:00:00Z",
  },
  {
    id: "4",
    name: "Call Her Daddy",
    youtubeChannelId: "@callherdaddy",
    rssFeedUrl: "https://callherdaddy.com/feed",
    category: "Lifestyle & Culture",
    imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400",
    createdAt: "2024-01-01T00:00:00Z",
    lastFetchedAt: "2024-11-01T00:00:00Z",
  },
  {
    id: "5",
    name: "The Diary of a CEO",
    youtubeChannelId: "@TheDiaryOfACEO",
    rssFeedUrl: "https://diaryofaceo.com/podcast",
    category: "Business & Entrepreneurship",
    imageUrl: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400",
    createdAt: "2024-01-01T00:00:00Z",
    lastFetchedAt: "2024-11-01T00:00:00Z",
  },
];

export const mockEpisodes: Episode[] = [
  {
    id: "e1",
    podcastId: "1",
    title: "#783: Hugh Jackman Returns — On Resilience, Reinvention, and Creative Risks",
    description: "Hugh Jackman returns to discuss his latest projects, philosophy on life, and creative process.",
    publishedDate: "2024-10-15",
    durationSeconds: 7200,
    youtubeUrl: "https://youtube.com/watch?v=example1",
    audioUrl: "https://audio.example.com/e1.mp3",
    guestNames: ["Hugh Jackman"],
    transcriptSource: "youtube",
    processingStatus: "completed",
    processedAt: "2024-10-15T12:00:00Z",
    createdAt: "2024-10-15T08:00:00Z",
  },
  {
    id: "e2",
    podcastId: "2",
    title: "Dr. Matthew Walker: Improve Sleep to Boost Mood & Emotional Regulation",
    description: "Dr. Matthew Walker discusses the science of sleep and its impact on mental health.",
    publishedDate: "2024-10-20",
    durationSeconds: 6300,
    youtubeUrl: "https://youtube.com/watch?v=example2",
    guestNames: ["Dr. Matthew Walker"],
    transcriptSource: "youtube",
    processingStatus: "completed",
    processedAt: "2024-10-20T12:00:00Z",
    createdAt: "2024-10-20T08:00:00Z",
  },
  {
    id: "e3",
    podcastId: "1",
    title: "#780: Rick Rubin — Magic, Wisdom, and Mystery from the Legendary Producer",
    description: "Rick Rubin shares his creative philosophy and approach to producing legendary albums.",
    publishedDate: "2024-10-10",
    durationSeconds: 8100,
    youtubeUrl: "https://youtube.com/watch?v=example3",
    guestNames: ["Rick Rubin"],
    transcriptSource: "youtube",
    processingStatus: "completed",
    processedAt: "2024-10-10T12:00:00Z",
    createdAt: "2024-10-10T08:00:00Z",
  },
  {
    id: "e4",
    podcastId: "3",
    title: "#2180: Naval Ravikant on Wealth, Happiness, and How to Read",
    description: "Naval Ravikant discusses his philosophy on creating wealth and finding happiness.",
    publishedDate: "2024-10-25",
    durationSeconds: 5400,
    youtubeUrl: "https://youtube.com/watch?v=example4",
    guestNames: ["Naval Ravikant"],
    transcriptSource: "youtube",
    processingStatus: "completed",
    processedAt: "2024-10-25T12:00:00Z",
    createdAt: "2024-10-25T08:00:00Z",
  },
  {
    id: "e5",
    podcastId: "5",
    title: "Mel Robbins: The Secret to Building Confidence",
    description: "Mel Robbins shares her techniques for building unshakeable confidence.",
    publishedDate: "2024-10-28",
    durationSeconds: 4800,
    youtubeUrl: "https://youtube.com/watch?v=example5",
    guestNames: ["Mel Robbins"],
    transcriptSource: "youtube",
    processingStatus: "completed",
    processedAt: "2024-10-28T12:00:00Z",
    createdAt: "2024-10-28T08:00:00Z",
  },
];

export const mockRecommendations: Recommendation[] = [
  // Books
  {
    id: "r1",
    episodeId: "e1",
    type: "book",
    title: "Meditations",
    author: "Marcus Aurelius",
    isbn: "978-0143036784",
    description: "A series of personal writings by Marcus Aurelius, Roman Emperor from 161 to 180 AD, recording his private notes to himself and ideas on Stoic philosophy.",
    coverImageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300",
    publisher: "Penguin Classics",
    publishedYear: 2006,
    pageCount: 304,
    goodreadsRating: 4.23,
    amazonUrl: "https://amazon.com/example",
    googleBooksUrl: "https://books.google.com/example",
    recommendationContext: "Hugh mentioned this as the book that fundamentally changed his perspective on stoicism and dealing with adversity in his acting career.",
    quoteFromEpisode: "This book has been on my nightstand for years. Every time I read it, I find something new that applies to whatever I'm going through.",
    timestampSeconds: 3845,
    recommendedBy: "Hugh Jackman",
    confidenceScore: 0.95,
    createdAt: "2024-10-15T12:30:00Z",
    updatedAt: "2024-10-15T12:30:00Z",
  },
  {
    id: "r2",
    episodeId: "e2",
    type: "book",
    title: "Why We Sleep",
    author: "Matthew Walker",
    isbn: "978-1501144325",
    description: "A comprehensive exploration of the science of sleep and why it matters more than we think.",
    coverImageUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=300",
    publisher: "Scribner",
    publishedYear: 2017,
    pageCount: 368,
    goodreadsRating: 4.36,
    amazonUrl: "https://amazon.com/example2",
    recommendationContext: "Dr. Walker's own book, which he discussed as containing the most comprehensive research on sleep science to date.",
    quoteFromEpisode: "I wrote this book because I realized how critical sleep is for every aspect of our mental and physical health, yet we're in a sleep deprivation crisis.",
    timestampSeconds: 450,
    recommendedBy: "Dr. Matthew Walker",
    confidenceScore: 0.98,
    createdAt: "2024-10-20T12:30:00Z",
    updatedAt: "2024-10-20T12:30:00Z",
  },
  {
    id: "r3",
    episodeId: "e3",
    type: "book",
    title: "The Creative Act: A Way of Being",
    author: "Rick Rubin",
    isbn: "978-0593652886",
    description: "A philosophical exploration of creativity and the artistic process from legendary music producer Rick Rubin.",
    coverImageUrl: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=300",
    publisher: "Penguin Press",
    publishedYear: 2023,
    pageCount: 432,
    goodreadsRating: 4.18,
    amazonUrl: "https://amazon.com/example3",
    recommendationContext: "Rick Rubin's own book about his creative philosophy developed over decades of producing legendary albums.",
    quoteFromEpisode: "This is everything I've learned about the creative process, distilled into principles anyone can use, whether you're making music or building a business.",
    timestampSeconds: 620,
    recommendedBy: "Rick Rubin",
    confidenceScore: 0.97,
    createdAt: "2024-10-10T12:30:00Z",
    updatedAt: "2024-10-10T12:30:00Z",
  },
  {
    id: "r4",
    episodeId: "e4",
    type: "book",
    title: "The Almanack of Naval Ravikant",
    author: "Eric Jorgenson",
    isbn: "978-1544514222",
    description: "A collection of Naval's wisdom on wealth creation and happiness, compiled from his tweets, podcasts, and essays.",
    coverImageUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300",
    publisher: "Magrathea Publishing",
    publishedYear: 2020,
    pageCount: 242,
    goodreadsRating: 4.52,
    amazonUrl: "https://amazon.com/example4",
    recommendationContext: "Naval praised this compilation of his ideas as the best summary of his philosophy on building wealth and finding happiness.",
    quoteFromEpisode: "Eric did an amazing job compiling my thoughts. If you want to understand my approach to life and business, this is the book to read.",
    timestampSeconds: 2100,
    recommendedBy: "Naval Ravikant",
    confidenceScore: 0.94,
    createdAt: "2024-10-25T12:30:00Z",
    updatedAt: "2024-10-25T12:30:00Z",
  },
  {
    id: "r5",
    episodeId: "e5",
    type: "book",
    title: "The 5 Second Rule",
    author: "Mel Robbins",
    isbn: "978-1682612385",
    description: "Transform your life, work, and confidence with everyday courage using Mel Robbins' simple 5-second technique.",
    coverImageUrl: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=300",
    publisher: "Savio Republic",
    publishedYear: 2017,
    pageCount: 240,
    goodreadsRating: 4.05,
    amazonUrl: "https://amazon.com/example5",
    recommendationContext: "Mel's own book about the technique that helped millions overcome hesitation and build confidence.",
    quoteFromEpisode: "The 5 Second Rule is the secret to changing anything about your life. It's so simple but incredibly powerful.",
    timestampSeconds: 1850,
    recommendedBy: "Mel Robbins",
    confidenceScore: 0.96,
    createdAt: "2024-10-28T12:30:00Z",
    updatedAt: "2024-10-28T12:30:00Z",
  },
  // Movies & TV Shows
  {
    id: "r6",
    episodeId: "e1",
    type: "movie",
    title: "The Prestige",
    creatorDirector: "Christopher Nolan",
    releaseYear: 2006,
    posterUrl: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=300",
    genre: ["Drama", "Mystery", "Sci-Fi"],
    runtimeMinutes: 130,
    rating: 8.5,
    streamingPlatforms: ["Netflix", "Amazon Prime"],
    recommendationContext: "Hugh discussed working with Christian Bale on this film and how it influenced his approach to method acting.",
    quoteFromEpisode: "Working on The Prestige with Chris Nolan taught me so much about commitment to a character. It's one of my favorite films I've been part of.",
    timestampSeconds: 4200,
    recommendedBy: "Hugh Jackman",
    confidenceScore: 0.92,
    createdAt: "2024-10-15T12:30:00Z",
    updatedAt: "2024-10-15T12:30:00Z",
  },
  {
    id: "r7",
    episodeId: "e3",
    type: "tv_show",
    title: "The Bear",
    creatorDirector: "Christopher Storer",
    releaseYear: 2022,
    posterUrl: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=300",
    genre: ["Drama", "Comedy"],
    runtimeMinutes: 30,
    seasons: 3,
    episodes: 28,
    rating: 8.6,
    streamingPlatforms: ["Hulu", "Disney+"],
    recommendationContext: "Rick praised the show's portrayal of creative pressure and the pursuit of excellence in a high-stress environment.",
    quoteFromEpisode: "The Bear is incredible. It captures the intensity of creating something great under pressure. Everyone should watch it.",
    timestampSeconds: 5400,
    recommendedBy: "Rick Rubin",
    confidenceScore: 0.90,
    createdAt: "2024-10-10T12:30:00Z",
    updatedAt: "2024-10-10T12:30:00Z",
  },
  {
    id: "r8",
    episodeId: "e4",
    type: "movie",
    title: "The Social Network",
    creatorDirector: "David Fincher",
    releaseYear: 2010,
    posterUrl: "https://images.unsplash.com/photo-1611348586804-61bf6c080437?w=300",
    genre: ["Biography", "Drama"],
    runtimeMinutes: 120,
    rating: 7.8,
    streamingPlatforms: ["Netflix", "Hulu"],
    recommendationContext: "Naval recommended this as an accurate portrayal of startup culture and the complexities of building a company.",
    quoteFromEpisode: "Despite the dramatization, The Social Network captures the essence of startup culture better than any other film.",
    timestampSeconds: 3200,
    recommendedBy: "Naval Ravikant",
    confidenceScore: 0.88,
    createdAt: "2024-10-25T12:30:00Z",
    updatedAt: "2024-10-25T12:30:00Z",
  },
  // Apps & Products
  {
    id: "r9",
    episodeId: "e2",
    type: "app",
    title: "Sleep Cycle",
    category: "Health & Wellness",
    description: "An intelligent alarm clock that analyzes your sleep patterns and wakes you during your lightest sleep phase.",
    url: "https://sleepcycle.com",
    imageUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=300",
    price: "Free / $29.99/year",
    recommendationContext: "Dr. Walker recommended this app for tracking sleep patterns and optimizing wake times.",
    quoteFromEpisode: "Sleep Cycle is one of the few sleep tracking apps that actually provides useful data without being intrusive.",
    timestampSeconds: 3600,
    recommendedBy: "Dr. Matthew Walker",
    confidenceScore: 0.87,
    createdAt: "2024-10-20T12:30:00Z",
    updatedAt: "2024-10-20T12:30:00Z",
  },
  {
    id: "r10",
    episodeId: "e5",
    type: "app",
    title: "Calm",
    category: "Meditation & Mindfulness",
    description: "The #1 app for meditation and sleep with guided meditations, sleep stories, and breathing programs.",
    url: "https://calm.com",
    imageUrl: "https://images.unsplash.com/photo-1528715471579-d1bcf0ba5e83?w=300",
    price: "$14.99/month",
    recommendationContext: "Mel uses Calm daily for meditation and recommended it for building a consistent mindfulness practice.",
    quoteFromEpisode: "I start every morning with Calm. It's been instrumental in helping me stay centered and focused.",
    timestampSeconds: 2800,
    recommendedBy: "Mel Robbins",
    confidenceScore: 0.89,
    createdAt: "2024-10-28T12:30:00Z",
    updatedAt: "2024-10-28T12:30:00Z",
  },
];

// Helper functions
export function getRecommendationsByType(type: string): Recommendation[] {
  return mockRecommendations.filter((rec) => rec.type === type);
}

export function getRecommendationsByEpisode(episodeId: string): Recommendation[] {
  return mockRecommendations.filter((rec) => rec.episodeId === episodeId);
}

export function getEpisodesByPodcast(podcastId: string): Episode[] {
  return mockEpisodes.filter((ep) => ep.podcastId === podcastId);
}

export function getPodcastById(id: string): Podcast | undefined {
  return mockPodcasts.find((p) => p.id === id);
}

export function getEpisodeById(id: string): Episode | undefined {
  return mockEpisodes.find((e) => e.id === id);
}

export function getRecommendationById(id: string): Recommendation | undefined {
  return mockRecommendations.find((r) => r.id === id);
}
